- name: Set Hostname
  ansible.builtin.shell: set-hostname rabbitmq

- name: Install Repo Rpms
  ansible.builtin.shell: curl {{ item }} | bash
  loop:
      - https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh
      - https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh

- name: Install RabbitMQ Server
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: installed

- name: Start RabbitMQ Service
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    enabled: yes

- name: Add Roboshop App User
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: "{{ lookup('aws_ssm', '{{env}}.roboshop.rabbitmq.MQ_PASS', region='us-east-1' ) }}"
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present