- name: Install Go
  ansible.builtin.dnf:
    name: golang
    state: installed

- name: Include App pre-Req
  ansible.builtin.include_tasks:
    file: app-prereq.yml

- name: Install Go Dependencies
  ansible.builtin.shell: go mod init dispatch ; go get ; go build
  args:
    chdir: /app

- name: SystemD Setup
  ansible.builtin.include_tasks:
    file: systemd.yml

- name: Load Schema
  ansible.builtin.include_tasks:
    file: schema.yml
  when: is_schema_needed