- name: Enable Nodejs
  ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Include App pre-Req
  ansible.builtin.include_tasks:
    file: app-prereq.yml

- name: Install Nodejs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Download pem file, DocDB
  ansible.builtin.get_url:
    url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
    dest: /app/rds-combined-ca-bundle.pem

- name: SystemD Setup
  ansible.builtin.include_tasks:
    file: systemd.yml

- name: Load Schema
  ansible.builtin.include_tasks:
    file: schema.yml
  when: is_schema_needed