groups:
  - name: Infra_alerts
    rules:
      - alert: ServerDownAlert
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Server Down Alert

      - alert: FrontendServiceDownAlert
        expr: node_systemd_unit_state{exported_name="nginx.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Frontend Service Down Alert

      - alert: BackendServiceDownAlert
        expr: node_systemd_unit_state{exported_name="backend.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Backend Service Down Alert

      - alert: MysqlServiceDownAlert
        expr: node_systemd_unit_state{exported_name="mysqld.service",state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Mysql Service Down Alert

      - alert: HighCPUusage
        expr: (100 - (avg by (name) (rate(node_cpu_seconds_total{mode="idle"}[1m])) * 100)) > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: High CPU Usage Alert

      - alert: HighMemoryusage
        expr: 100 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes * 100) > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: High Memory Usage Alert